version: '3.5'


services:

    neo4j:
        container_name: devneo4j
        hostname: neo4j
        image: neo4j:5.15.0-community

        ports:
            - 7474:7474
            - 7687:7687

        restart: always

        volumes:
            - $HOME/neo4j/data:/data
            - $HOME/neo4j/conf/:/conf
            - $HOME/neo4j/logs:/logs

        environment:
            - NEO4J_AUTH=none
            - NEO4J_DATABASE=llmware
